---
hostname: localhost
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_plugins:
  - git
  - sonar
  - ssh
  - gradle
  - greenballs
  - rundeck
  - delivery-pipeline-plugin
  - build-pipeline-plugin
  - job-dsl
  - nested-view
  - parameterized-trigger
  - compact-columns
  - extra-columns
  - thinBackup
  - timestamper
  - jobConfigHistory
  - envinject 
  - ghprb
  - stash-pullrequest-builder
  - stashNotifier
  - plain-credentials 
  - credentials-binding
  - build-name-setter
  - build-monitor-plugin
  - claim
  - build-timeout
  - email-ext
  - parameterized-trigger
  - rebuild
  - heavy-job
  - buildgraph-view
  - JDK_Parameter_Plugin
  - git-parameter 
  - downstream-buildview
  - mask-passwords
  - repository-connector
  - dashboard-view
  - global-build-stats
