---

grafana_git_url: https://github.com/torkelo/grafana.git
grafana_graphite_root: /opt/graphite
grafana_version: 1.6.1
grafana_vhost_server_name: grafana
grafana_port: 8080

grafana_elasticsearch_url: http://{{ elasticsearch_host }}:9200
grafana_graphite_url: http://{{ graphite_host }}

