---
  - name: Download nexus
    get_url: url={{ sonatype_nexus_download_url }} dest={{ sonatype_nexus_download_dest }}
    register: nexus_download

  - name: Get Nexus directory
    shell: "tar -tf {{ sonatype_nexus_download_dest }} | egrep '^nexus-' | cut -d/ -f1 | uniq"
    changed_when: false
    register: nexus_directory

  - name: Extract Nexus
    command: tar xzf {{ sonatype_nexus_download_dest }} chdir=/opt
    when: nexus_download.changed
    notify:
      - restart sonatype-nexus

  - name: Create and own working directories
    file: dest={{ item }} owner=nexus group=nexus recurse=true state=directory
    with_items:
      - "{{ sonatype_nexus_work_dir }}"
      - "{{ sonatype_nexus_work_dir }}/plugin-repository"
      - "{{ sonatype_nexus_pid_dir }}"
      - "{{ sonatype_nexus_root_dir }}/{{ nexus_directory.stdout }}/logs"
    notify:
      - restart sonatype-nexus
